apiVersion: v1
kind: Service
metadata:
  name: helloworld
  labels:
    app: helloworld
    service: helloworld
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: helloworld
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: helloworld-set
  labels:
    app: helloworld
    version: v1
spec:
  serviceName: "helloworld"
  replicas: 5
  selector:
    matchLabels:
      app: helloworld
      version: v1
  template:
    metadata:
      labels:
        app: helloworld
        version: v1
    spec:
      containers:
      - name: helloworld
        image: docker.io/istio/examples-helloworld-v1
        resources:
          requests:
            cpu: "1m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 5000
