apiVersion: v1
kind: ServiceAccount
metadata:
  name: getpods-sa
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: getpods
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["extensions", "apps"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["get", "watch", "list"]
---
# even though the serviceaccount was created, just relying on the
# default serviceaccount on the pods at this point.  Downside is every
# pod can now list things, but that's it....
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: default
  name: getpods
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
  - kind: ServiceAccount
    name: getpods-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: getpods
  apiGroup: rbac.authorization.k8s.io

  
