apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: helloworld-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: helloworld
spec:
  hosts:
  - "*"
  gateways:
  - helloworld-gateway
  http:
  - match:
    - uri:
        exact: /hello
    route:
    - destination:
        host: helloworld
        port:
          number: 5000
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: helloworld-versionrule
spec:
  host: helloworld
  subsets:
#@ for i in range(0,90):
  - name: #@ "p" + str(i)
    labels:
      statefulset.kubernetes.io/pod-name: #@ "helloworld-set-" + str(i)
#@ end
#@ for i in range(0,90):
#@ port = 10000 + i
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: #@ "helloworld-tcpgw" + str(port)
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: #@ port
      name: tcp
      protocol: TCP
    hosts:
    - "*"
---		      
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: #@ "hwtcpvs" + str(i)
spec:
  hosts:
  - "*"
  gateways:
  - #@ "helloworld-tcpgw" + str(port)
  tcp:
  - match:
    - port: #@ port
    route:
    - destination:
        host: helloworld
        subset: #@ "p" + str(i)
        port:
          number: 5000
#@ end
