apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoyproxy
  labels:
    app: envoyproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: envoyproxy
  template:
    metadata:
      labels:
        app: envoyproxy
    spec:
      containers:
      - name: envoyproxy
        image: "blowekaacr.azurecr.io/envoy/envoy"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        - name: envoy-admin
          containerPort: 9902
        volumeMounts:
        - name: podscanner
          mountPath: /podscanner
      volumes:
        - name: podscanner
          configMap:
            name: podscannerconfig
      imagePullSecrets:
        - name: acr-secret
          

